{include file="header.tpl"}
<section class="vh-100 ">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card border-dark " style="border-radius: 1rem;">
          <div class="card-body p-5 ">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h3 class="fw-bold mb-5 text-uppercase">Security Verification</h3>
                {if $alert}
            <div class="{$alert_class}">
                <span>{$alert_message}</span>
            </div>
            {/if}
            <form  method="post">
                {if $settings.$action.pin_code}
                <p class=" mb-1">Enter your account transaction pin code </p>
              <div class="form-outline  mb-2">
                  <label class="form-label" >Enter Transaction Code</label>
                <input type="number" name="pin_code" class="form-control " />
              </div>
              {/if} {if $settings.$action.2fa_code}
                 <p class=" mb-1">Enter your 6 digit code generated by the Authenticator App </p>
              <div class="form-outline  mb-2">
                  <label class="form-label" >Enter 2FA Code</label>
                <input type="number" name="2fa_code" class="form-control"  />
              </div>
              {/if} {if $settings.$action.email_code}
                <p class=" mb-1">Enter your 6 digit code sent to your email</p>
              <div class="form-outline  mb-2">
                  <label class="form-label" >Enter Email Code</label>
                <input type="number" name="email_code" class="form-control"  />
                <input type="button" class="btn btn-sm btn-primary" value="send" id="otp_button" onclick="getotp()">
              </div>
              {/if}
              <button  class="btn btn-outline-primary btn-lg px-5 " type="submit" name="confirm">Confirm</button>

            </form>

            </div>

            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{include file="footer.tpl"}

{literal}
<script>
function getotp() {
var element = document.getElementById("otp_button");
    element.disabled = true;
    setTimeout(function(){  
        element.disabled = false;
    }, 60000);
    const xmlhttp = new XMLHttpRequest();
    xmlhttp.onload = function() {
    	alert(this.responseText);
	}
	xmlhttp.open("GET", "?send_otp");
	xmlhttp.send();
}
</script>
{/literal}